### ISSUE TITLE
Missing input files for rule kallisto_index:

### ISSUE THREAD

**Issue by trishorts** [snakemake-workflows/rna-seq-kallisto-sleuth#27]
Sorry if this is a dumb question. I'm very new to snakemake. I got the following error and I don't know how to fix it.

MissingInputException in line 1 of /home/user/GitClones/rna-seq-kallisto-sleuth/workflow/rules/quant.smk:
Missing input files for rule kallisto_index:
resources/ref/Homo-sapiens.GRCh38.cdna.chr21.fa

This is probably not what I am supposed to do but I downloaded kallisto indexes and put them in the /resources/ref/ directory hoping it would solve the problem. It did not. Anyway fasta is not divided by chromosome.

Any help would be appreciated.

**Comment by dlaehnemann** [comment]
All the adaptations you might have to do should be to the files in the `config/` folder:
https://github.com/snakemake-workflows/rna-seq-kallisto-sleuth#step-2-configure-workflow

In `config/config.yaml` you can set your reference at:
https://github.com/snakemake-workflows/rna-seq-kallisto-sleuth/blob/3cd43dbaaea80c53a952807c0869a65de6679479/config/config.yaml#L6

And you can set this to any fasta file you want, but that fasta file should be found at that relative path (from the root directory of your repo clone). kallisto then creates its own index. If you want to find out what kind of file your workflow is missing in general and what it is needed for, search for the rules' name in the `.smk` files in the `workflow/rules/` directory to see what its input and output are, and what it actually runs. If it calls a wrapper (`wrapper:`), you can head over to their docs to find out what exactly it does:
https://snakemake-wrappers.readthedocs.io/en/stable/

Optimally, the workflow would also do the reference download for you, but this hasn't been implemented yet.

**Comment by dlaehnemann** [comment]
Closing as inactive (and out of date). If something similar comes up, please just open another issue and reference this one.
