### ISSUE TITLE
conda command not available despite singularity

### ISSUE THREAD

**Issue by chrishah** [snakemake-workflows/rna-seq-kallisto-sleuth#3]
Hi,

First of all thanks for making this workflow available - looking forward to using it!

I was trying to run the pipeline via `--use-conda --use-singularity`, but when trying `snakemake -n --use-singularity --use-conda --cores 10` I get an error, saying that conda is not available:

```
Building DAG of jobs...
Singularity image docker://continuumio/miniconda3 will be pulled.
CreateCondaEnvironmentException:
The 'conda' command is not available in the shell /usr/bin/bash that will be used by Snakemake. You have to ensure that it is in your PATH, e.g., first activating the conda base environment with `conda activate base`.

``` 

This is odd, since my understanding was that everything should run within the miniconda3 container, where conda should of course be available. Or am I misunderstanding something here? Perhaps I am just doing something wrong..

I just tried to enter the relevant miniconda3 container:
```
singularity shell docker://continuumio/miniconda3
```
and in there `conda` is in the path.

I am using snakemake version 5.4.5 and singularity version 2.6.1-dist.

Thanks in advance for any comments/help!

Best wishes,
Christoph

**Comment by johanneskoester** [comment]
Yes, you are right, this might be a bug. I'll have a look.

**Comment by johanneskoester** [comment]
Fixed in the Snakemake master branch now. I will release a new version soon.

**Comment by chrishah** [comment]
Hi,

Thanks for fixing this so quickly! pulled the latest commit, rebuild snakemake and it seems to work now! Thanks!

cheers,
Christoph
