### ISSUE TITLE
config.yaml is not part of the release download

### ISSUE THREAD

**Issue by cmeesters** [snakemake-workflows/rna-seq-kallisto-sleuth#56]
Hi,

very nice workflow! I would, however, suggest including the config-directory as a sample directory in the release, otherwise users have to download everything separately (or clone the development branch).

Best regards
Christian

**Comment by johanneskoester** [comment]
Thanks! As the readme says, the usage is described in the workflow catalog, see here: https://snakemake.github.io/snakemake-workflow-catalog?usage=snakemake-workflows/rna-seq-kallisto-sleuth

When following the steps over there, you get a correct deployment of the workflow including the template config. It is no longer best practice to simply clone snakemake workflows. Instead one uses them as modules like shown in the catalog link above. The advantage is that it becomes very easy to follow the upstream versions and also to compose multiple workflows together.
