### ISSUE TITLE
Whitespaces in config/units.tsv 

### ISSUE THREAD

**Issue by aFienemann** [snakemake-workflows/rna-seq-kallisto-sleuth#81]
Hello,

i am currently trying to run step 4 of the Workflow:
`snakemake --cores all --use-conda`

Apparently whitespaces are detected in columns fq1 and fq2 in config/**units.tsv**

![Screenshot from 2023-10-13 10-38-59](https://github.com/snakemake-workflows/rna-seq-kallisto-sleuth/assets/147806402/3930efee-d058-4179-983a-0ef771b28240)

But there are none in the file, the path is functional. I used LibreOffice to customize the table, but in the Text Editor everything looks fine (Tab-seperated and no additional whitespaces). Am I missing something obvious? Still quite new in the field.

Thanks a lot!

**Comment by tedil** [comment]
Are you by any chance using python 3.12? If so, this might be this issue: https://github.com/snakemake/snakemake/issues/2480

**Comment by aFienemann** [comment]
That was indeed the case. Thanks a lot!
